--INSERT Registros Tipo Notificacion
INSERT INTO TBL_TIPO_NOTIFICACION (CODIGO_TIPO_NOTIFICACION, TIPO_NOTIFICACION)
VALUES (TBL_TIPO_NOTIFICACION_CODIGO_T.NEXTVAL, 'Seguimiento');

INSERT INTO TBL_TIPO_NOTIFICACION (CODIGO_TIPO_NOTIFICACION, TIPO_NOTIFICACION)
VALUES (TBL_TIPO_NOTIFICACION_CODIGO_T.NEXTVAL, 'Comentario');

INSERT INTO TBL_TIPO_NOTIFICACION (CODIGO_TIPO_NOTIFICACION, TIPO_NOTIFICACION)
VALUES (TBL_TIPO_NOTIFICACION_CODIGO_T.NEXTVAL, 'Reacción');

INSERT INTO TBL_TIPO_NOTIFICACION (CODIGO_TIPO_NOTIFICACION, TIPO_NOTIFICACION)
VALUES (TBL_TIPO_NOTIFICACION_CODIGO_T.NEXTVAL, 'Añadio historia');



--INSERT Resgistros Estado Notificacion
INSERT INTO TBL_ESTADO_NOTIFICACION (CODGIO_ESTADO_NOTIFICACION, ESTADO_NOTIFICACION)
VALUES (TBL_ESTADO_NOTIFICACION_CODGIO.NEXTVAL, 'Vista');

INSERT INTO TBL_ESTADO_NOTIFICACION (CODGIO_ESTADO_NOTIFICACION, ESTADO_NOTIFICACION)
VALUES (TBL_ESTADO_NOTIFICACION_CODGIO.NEXTVAL, 'Pendiente');